[project]
name = "s1bench"
version = "1.0"
dependencies = ["accelerate", "datasets", "flash-linear-attention", "httpx", "kagglehub", "peft", "torch", "transformers"]

[project.scripts]
s1bench = "s1bench.__main__:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["s1bench", "s1bench.tasks"]
