from functools import partial

from . import (
    aym,
    belebele,
    bev,
    biltweetnews,
    checkworthy,
    emotion,
    exams,
    guardrails,
    hateday,
    irony,
    jev_bench,
    jev_noul,
    judging,
    lavoir,
    massive,
    mide22,
    neural_news,
    news,
    nli,
    offenseval,
    piqa,
    reviews,
    rtp_lx,
    seahorse,
    spam,
    stsb,
    tools,
    touche,
    turblimp,
    webfaq,
    xcopa,
    xfact,
    xsid,
)

SECONDARY = {
    **{f"jevbench_{config}_tr": partial(jev_bench.build, config) for config in jev_bench.CONFIGS},
    "bev_tr": bev.build,
    "lavoir_zeroshot_tr": lavoir.build,
    "rtp_lx_tr": rtp_lx.build,
    "injection_tr": guardrails.build_injection,
    "over_refusal_tr": guardrails.build_over_refusal,
    "xl_safety_tr": guardrails.build_xl_safety,
    "ragtruth_tr": judging.build_ragtruth,
    "rewardbench_tr": judging.build_rewardbench,
    "wmt_da_tr": judging.build_wmt,
    "tool_choice_tr": tools.build,
    "irony_tr": irony.build,
    "neural_news_tr": neural_news.build,
    "tus21_tr": exams.build_tus21,
    "global_piqa_tr": piqa.build,
    "xfact_tr": xfact.build,
    "mide22_tr": mide22.build,
    "aym_outcome_tr": aym.build,
    "turkishmmlu_difficulty_tr": exams.build_turkishmmlu_difficulty,
}

TASKS = {
    "massive_intent_tr": massive.build,
    "belebele_tr": belebele.build,
    "xcopa_tr": xcopa.build,
    "include_tr": exams.build_include,
    "global_mmlu_tr": exams.build_global_mmlu,
    "nli_tr": nli.build,
    "xfact_teyit_tr": xfact.build_teyit,
    "offenseval_tr": offenseval.build,
    "jev_noul_tr": jev_noul.build,
    "jev_noul_unseen_tr": jev_noul.build_unseen,
    "buyuksinema_tr": reviews.build_buyuksinema,
    "musteri_yorumlari_tr": reviews.build_musteri_yorumlari,
    "stsb_tr": stsb.build,
    "xsid_tr": xsid.build,
    "sms_spam_tr": spam.build,
    "seahorse_tr": seahorse.build,
    "webfaq_tr": webfaq.build,
    "checkthat_tr": checkworthy.build_checkthat,
    "trclaim19_tr": checkworthy.build_trclaim19,
    "biltweetnews_tr": biltweetnews.build,
    "hateday_tr": hateday.build,
    "news_topic_tr": news.build,
    "tweet_emotion_tr": emotion.build,
    "turkishmmlu_tr": exams.build_turkishmmlu,
    "touche_tr": touche.build,
    "turblimp_tr": turblimp.build,
    **SECONDARY,
}

AREAS = {
    "routing": ["massive_intent_tr", "xsid_tr", "news_topic_tr"],
    "opinion": ["buyuksinema_tr", "musteri_yorumlari_tr", "biltweetnews_tr", "tweet_emotion_tr"],
    "safety": ["offenseval_tr", "sms_spam_tr", "hateday_tr"],
    "fact_checking": ["xfact_teyit_tr", "checkthat_tr", "trclaim19_tr"],
    "judging": ["seahorse_tr", "webfaq_tr"],
    "workflow": ["jev_noul_tr", "jev_noul_unseen_tr"],
    "politics": ["touche_tr"],
    "language": ["nli_tr", "stsb_tr", "belebele_tr", "xcopa_tr", "turblimp_tr"],
    "knowledge": ["include_tr", "global_mmlu_tr", "turkishmmlu_tr"],
}

# the area tasks every model answered: all but MASSIVE, which Metask skips
MAIN = [task for tasks in AREAS.values() for task in tasks if task != "massive_intent_tr"]
